### ISSUE TITLE
Unnecessary stuff in git repository (venv, .idea)

### ISSUE THREAD

**Issue by ShkarupaDC** [FreeLike76/Pacman-with-AI#1] opened 2021-09-30 19:19 UTC
Try to use .gitignore and manage your dependencies using requirements.txt (pip freeze > requirements.txt) :))

**Comment by FreeLike76** [comment] 2021-09-30 19:51
I believe the problem is now fixed. Thanks for pointing that out!

**Closed as completed by FreeLike76** 2021-09-30 19:51 UTC
